project:
  title: "PLFM"
  type: website

resources:
  - "assets/*"

website:
  title: "PLFM"
  search: false
  navbar:
    title: "PLFM @ DCC"
    background: "#004a7e"
    logo-alt: PLFM
    tools:
      - icon: github
        href: https://github.com/plfm-dcc/plfm-dcc.github.io
    left:
      - text: "Home"
        href: index.qmd
      - pages/people.qmd
      - pages/research.qmd
      - pages/education.qmd
      - pages/events.qmd
      - pages/resources.qmd
      - pages/blog.qmd
      # - pages/news.qmd
    pinned: true

format: 
  html:
    theme: cosmo
    css: styles.css
    page-layout: full
    toc: false
    anchor-sections: false
    # embed-resources: true