project:
  type: website

website:
  title: "PLFM"
  search: false
  navbar:
    title: "PLFM @ DCC"
    logo: /assets/favicon.png
    logo-alt: PLFM
    background: primary
    tools:
      - icon: github
        href: https://github.com
    left:
      - people.qmd
      - research.qmd
      - education.qmd
      - resources.qmd
      - events.qmd
      - news.qmd
    pinned: true
  favicon: /assets/favicon.png

format: 
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



