project:
  title: "PLFM"
  type: website

website:
  title: "PLFM"
  search: false
  navbar:
    title: "PLFM @ DCC"
    # logo: /assets/logo.png
    logo-alt: PLFM
    background: primary
    tools:
      - icon: github
        href: https://github.com
    left:
      - pages/people.qmd
      - pages/research.qmd
      - pages/education.qmd
      - pages/events.qmd
      - pages/resources.qmd
      - pages/blog.qmd
      - pages/news.qmd
    pinned: true
  # favicon: /assets/favicon.png

format: 
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
    # embed-resources: true